### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by starptr** [H5O2plus/Simple-Statistics#3]
- [x] a **good** readme page
- [x] UML diagram
- [x] append
- [x] removen
- [x] empty
- [x] feed
- [x] search
- [x] array index operator[]
- [x] length_unique
- [x] length_total
- [x] unique_set
- [x] get_mode in O(1)
- [x] get_median in O(1)
- [x] get_mean in O(1)
- [x] get_SD in O(1)
- [x] get_min in O(1)
- [x] get_max in O(1)
- [x] default constructor (empty data struct)
- [x] constructor that accepts std iteration-supported container
- [x] no cmath or math.h

**Comment by KenTaniguchi-R** [comment]
I added append and remove methods but there is a problem in the function which are used in these methods. I could not figure out what is a problem
